version: '3.9'

services:
  user_service:
    build: ./user_service
    ports:
      - "8000:8000"
    env_file:
      - ./user_service/.env
    depends_on:
      - user_db
    volumes:
      - ./user_service:/app
    restart: always

  user_db:
    image: postgres:15
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  restaurant_service:
    build: ./restaurant_service
    ports:
      - "8001:8001"
    env_file:
      - ./restaurant_service/.env
    environment:
      - PYTHONPATH=/app
    depends_on:
      - restaurant_db
    volumes:
      - ./restaurant_service:/app
    restart: always

  restaurant_db:
    image: postgres:15
    environment:
      POSTGRES_DB: restaurant_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata_restaurant:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  pgdata_restaurant:
